FROM tfwnicholson/vim

MAINTAINER Tom Nicholson "https://github.com/tomssem/"

RUN python3 -m pip install --upgrade pip
RUN pip3 install scipy numpy pandas scikit-learn jupyterlab arrow gpflow matplotlibstatsmodels tensorflow tensorflow-probability 

CMD ["/bin/bash"]
